### ISSUE TITLE
Switching from setup-go causes error

### ISSUE THREAD

**Issue by Jacalz** [WillAbides/setup-go-faster#11]
I had a fully working action with `setup-go` and wanted to port it to use `setup-go-faster` instead, however, it looks like it fails when using this action. I think it might be an issue in how it sets up the environment and I hope that we perhaps could get this fixed :slightly_smiling_face: 

https://github.com/Jacalz/fyne/actions/runs/575320403/workflow

The error is this one:
```
Run shogo82148/actions-goveralls@v1
/home/runner/work/_actions/shogo82148/actions-goveralls/v1/bin/goveralls_linux_amd64 -coverprofile=coverage.out -service=github -ignore=
15:50:17 gocover.go:111: Can't find can't find "animation.go": go/build: go list fyne.io/fyne/v2/: exit status 2
go: cannot find GOROOT directory: /usr/local/go

Error: The process '/home/runner/work/_actions/shogo82148/actions-goveralls/v1/bin/goveralls_linux_amd64' failed with exit code 1
```

**Comment by WillAbides** [comment]
Thanks for trying out setup-go-faster, and thanks even more for taking the time to send an issue when it didn't work out.

I was able to get it working in the commit below by explicitly setting GOROOT in the goveralls workflow step. Setup-go-faster doesn't set the GOROOT environment variable because it is [supposedly unnecessary](https://dave.cheney.net/2013/06/14/you-dont-need-to-set-goroot-really). Instead it unsets it and relies on go's standard behavior to work out GOROOT.  However, that decision appears to have been a mistake. I will update update setup-go-faster to set GOROOT in the near future.

In the mean time, I hope setting GOROOT in the workflow unblocks you.  Let me know if it doesn't.

https://github.com/WillAbides/fyne/commit/fcc38673e076be9a7159b6d8bcad2c2020ddb0b8

**Comment by Jacalz** [comment]
Thank you very much for looking into it. I will need to rebase my branch on the latest upstream work on our CI infrastructure for further tests, but your change does indeed look like it fixes the issue 🙂

**Comment by Jacalz** [comment]
Thanks for your help with this @WillAbides. I have now rebased and updated with your workaround. Thank you :slightly_smiling_face:

**Comment by Jacalz** [comment]
I can't find any commit that fixed this. Am I missing something?
