### ISSUE TITLE
Why not upstream?

### ISSUE THREAD

**Issue by mohammed90** [WillAbides/setup-go-faster#6]
Given you're able to shave so many seconds setting up Go, any reason the hack isn't upstreamed to actions/setup-go?

**Comment by WillAbides** [comment]
I hope this does eventually get pulled into `actions/setup-go` in some form.

It's been just 8 days since the first commit to this project. I don't expect the setup-go maintainers to be interested in pulling this in just yet.

I'm afraid the biggest performance improvement would be a breaking change too. Most of the improvement to Windows installs comes from installing to `RUNNER_WORKSPACE` instead of `RUNNER_TOOL_CACHE`, and there are probably some users of `setup/go` who expect it to end up in `RUNNER_TOOL_CACHE`.

🤞 for this eventually becoming `actions/setup-go@v3`
